### ISSUE TITLE
Is Latest version (4.1.7) 64bit?

### ISSUE THREAD

**Issue by rmingas** [suratovvlad/qbittorrent-installer#24]
I downloaded The latest version and noticed during installation that it goes to "Program Files (x86)" folder and doesn't upgrade previous version (4.1.6-1) installed on "Program Files" folder. Is 64bit not included?

Windows 10 Pro 64 bits edition

**Comment by suratovvlad** [comment]
It is 64 bit version, however, this happens because of changed version of Qt IFW.
Before 4.1.7 I used 64bit version of Qt IFW from MSYS2, which is compiled with Qt 5.12.
However, the Qt IFW is not compatible yet with this version according https://bugreports.qt.io/projects/QTIFW/issues/QTIFW-1405.

This incompatibility causes this issue #8 #11 #17  #21. 
I decided to prevent users from posting same thing.

So, now (temporary) I use official build from [qt.io](https://download.qt.io/official_releases/qt-installer-framework/3.1.1/), which is only x86 and compiled with 5.9, so, it offers only "Program Files (x86)" directory
